title = "Arcaneum Framework"  # From Git
gitRepoUrl = "https://github.com/MFSRoblox/ArcaneumFramework/" # From Git

gitSourceBranch = "main"
changelog = true
[[classOrder]]
section = "Class Functions"
collapsed = false # Determines with the section grouping is collapsed or expanded on page load. Defaults to true.
classes = ["BaseClass","Class", "InternalClass"]

[[classOrder]]
section = "Globals"
collapsed = false # Determines with the section grouping is collapsed or expanded on page load. Defaults to true.
classes = ["Utilities"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "MFSRoblox"
projectName = "ArcaneumFramework"
url = "https://MFSRoblox.github.io"
baseUrl = "/ArcaneumFramework/"
tagline = "main"

[footer]
style = "dark"