# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  #lint:
  #  name: Lint
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Checkout code
  #    uses: actions/checkout@v2

  #  - uses: Roblox/setup-foreman@v1
  #    name: Install Foreman
  #    with:
  #        version: "^1.0.0"
  #        token: ${{ SECRETS.GITHUB_TOKEN }}

  #  - name: Lint
  #    run: |
  #      selene ./modules
  roblox-tests:
    name: Roblox Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Test Place
        run: rojo build default.project.json -o test.rbxl

      - name: Run Tests
        shell: bash
        run: run-in-roblox --place test.rbxl --script ./src/ServerScriptService/ServerScriptsLoader/init.server.lua > test-out.txt
        continue-on-error: true
        
      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed" || (cat test-out.txt && exit 1)
  moonwave-tests:
    name: Moonwave Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Moonwave
        run: npm i -g moonwave

      - name: Test Build
        run: moonwave build